<?xml version="1.0" encoding="UTF-8" ?> 
<coverage generated="$mtime$" clover="3.0.2" xmlns="http://schemas.atlassian.com/clover3/report">
   <project timestamp="$mtime$" name="bullshtml result">
      	<metrics coveredelements="$summary.coveredElementCount$" elements="$summary.elementCount$" coveredconditionals="$summary.coveredBranchCount$" conditionals="$summary.branchCount$" coveredmethods="$summary.coveredFunctionCount$" methods="$summary.functionCount$" coveredstatements="0" statements="0" />
$parentDirList:{ eachDir |	
        $eachDir:/cloverSrcDir()$
}$
   </project>
</coverage>
